# Generated by Django 3.0.6 on 2020-06-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_conatct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='conatct',
        ),
    ]
